title: Milom's Projects
email: milom.apps@gmail.com
description: >-
  Apps and projects by Milom. Support pages, privacy policies, and information about my iOS and Android apps.
baseurl: ""
url: ""
github_username: mil0m

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Only show these pages in the header navigation
header_pages:
  - SkogskarlenBooking.markdown
  - HeroRealmsLifeCounter.markdown
